"""This module defines the Unreal Engine feature for Jenkins pipelines.
It includes configurations for building Unreal projects using Unreal Build Graph"""

import importlib
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, ValidationInfo, model_validator
from mako.template import Template

from generator import logger
from generator.core.base_feature import BaseFeature, FeatureConfig
from generator.core.template_context import TemplateContext
from generator.utils.graph import Graph

TEMPLATE = """
    def buildgraph_properties = "${ctx.inlined_properties}"

    def buildgraph_job_groups = [
% for platform_name,platform in ctx.platforms.items():
    % for group_names in platform.parallel_groups:
        [
        % for group_name in group_names:
            [
                "${group_name}": [
                    tasks: [ ${", ".join(f'"{node.name}"' for node in platform.groups[group_name].nodes)} ],
                    platform: "${platform_name}"
                ],
            ],
        % endfor
        ],
    % endfor
% endfor
    ]

    buildgraph_job_groups.each { group ->
        executeJobsInParallel(group, buildgraph_properties)
    }
"""


class UnrealBuildGraphPostTasksConfig(BaseModel):
    """Configuration for post tasks in Unreal Build Graph."""

    enabled: bool = Field(
        default=True,
        description="If true, runs the post tasks (recordIssues) after the buildgraph tasks.",
    )
    archive_artifacts: Optional[bool] = Field(
        default=True,
        description="If true, archives the artifacts generated by the recordIssues tasks.",
    )


class UnrealBuildGraphConfig(BaseModel):
    """Configuration for Unreal Build Graph tasks."""

    target: str = Field(description="The target to build with Build Graph.")
    node_name_filters: Optional[Dict[str, str]] = Field(
        default=None,
        description="Filters to apply to the node names. Keys are the buildgraph task names and values are the jenkins node filter (Ex: `'MyGame Editor Win64 Test=BootTest': '!NoGPU'` will not select machine without a GPU to run the BootTest task).",
    )
    properties: Optional[Dict[str, str]] = Field(
        default=None,
        description="Properties to pass to build graph. These are passed as -set:PropertyName=PropertyValue arguments to UAT.",
    )
    pre_tasks: Optional[List[str]] = Field(
        default=None,
        description="List of tasks to run before the buildgraph tasks. These are run as shell commands. (Ex: `'pwsh script: \"Scripts/Project/CI/CI_NetUse.ps1\"'`)",
    )
    post_tasks: Optional[UnrealBuildGraphPostTasksConfig] = Field(
        default_factory=UnrealBuildGraphPostTasksConfig(),
        description="Options to record issues on the logs generated by the buildgraph tasks",
    )


class UnrealCleanupConfig(BaseModel):
    """Configuration for cleanup tasks after the buildgraph tasks."""

    enabled: Optional[bool] = Field(
        default=True,
        description="If true, runs the cleanup tasks after the buildgraph.",
    )
    additional_node_name: Optional[str] = Field(
        default=None,
        description="Additional jenkins node tags to use if you want the cleanup tasks to be executed on specific nodes.",
    )


class UnrealProjectConfig(BaseModel):
    """Configuration model for the project section of Unreal."""

    uproject_path: Path = Field(
        description="The path to the .uproject file of the Unreal project."
    )
    pyscripts_folder: Path = Field(
        default_factory=lambda: None,
        description="Path to the PyScripts folder if it's not at the root of the uproject",
    )
    # Done like this to make it optional in the config file 
    # but will try to be set to a relative path from the uproject_path

    @model_validator(mode="after")
    def validate_model(self, info: ValidationInfo) -> "UnrealProjectConfig":
        """Validation of the project config model 
        and try to resolve paths to the uproject file and pyscripts folder."""
        if not self.uproject_path.is_absolute():
            config_file_path = (
                info.context.get("config_file_path") if info.context else None
            )

            if config_file_path:
                # Resolve relative to config file directory
                config_dir = Path(config_file_path).parent
                self.uproject_path = (config_dir / self.uproject_path).resolve()
                logger.debug(
                    "Resolved uproject_path relative to config file: %s",
                    self.uproject_path,
                )
            else:
                return None

        if not self.uproject_path.is_file():
            raise ValueError("uproject_path does not point to a valid file")

        logger.info("Resolved uproject_path: %s", self.uproject_path)

        if self.pyscripts_folder is None:
            logger.debug("pyscripts_folder is not set. Default to PyScripts")
            self.pyscripts_folder = Path("PyScripts")

        if not self.pyscripts_folder.is_absolute():
            uproject_path = self.uproject_path
            if uproject_path is None:
                raise ValueError(
                    "uproject_path must be validated before pyscripts_folder"
                )

            logger.debug(
                "pyscripts_path is a relative path, resolving against the uproject located at %s",
                uproject_path,
            )

            self.pyscripts_folder = uproject_path.parent / self.pyscripts_folder

        if not self.pyscripts_folder.is_dir():
            raise ValueError(f"Pyscripts folder not found at {self.pyscripts_folder}.")

        logger.info("Resolved pyscripts_folder: %s", self.pyscripts_folder)
        return self


class UnrealConfig(FeatureConfig):
    """Configuration model for the unreal feature."""

    project: UnrealProjectConfig = Field(
        description="The Unreal project configuration."
    )
    buildgraph: UnrealBuildGraphConfig = Field(
        description="The buildgraph configuration."
    )
    cleanup_after_build: Optional[UnrealCleanupConfig] = Field(
        default=None, description="Options to run post-buildgraph cleanup tasks."
    )


class UnrealFeature(BaseFeature):
    """Feature for using Unreal Engine."""

    feature_name = "unreal"

    def should_include(self, config: Dict[str, Any]) -> bool:
        return "unreal" in config

    def get_config_model(self) -> BaseModel:
        return UnrealConfig

    @property
    def dependencies(self) -> List[str]:
        return ["utils"]

    def render_block(self, block_type: str, context: TemplateContext, template) -> str:
        if block_type == "build_steps":
            jenkins_jobs = self.get_jenkins_jobs(context.feature_config)
            context.feature_config._accumulator["jenkins_jobs_output"] = jenkins_jobs

        return super().render_block(block_type, context, template)

    def get_jenkins_jobs(self, config: UnrealConfig) -> str:
        """Generate the Jenkins jobs for Unreal."""
        module_path = config.project.pyscripts_folder
        module_name = "uepyscripts.run.buildgraph"

        abs_package_root = os.path.abspath(module_path)
        if abs_package_root not in sys.path:
            sys.path.insert(0, abs_package_root)

        uepyscripts = importlib.import_module(module_name)

        temp_folder = uepyscripts.project.project_folders.saved_folders.temp
        temp_folder.mkdir(parents=True, exist_ok=True)

        export_path = temp_folder.joinpath("buildgraph.json")

        extra_parameters = [f"-Export={export_path}", "uebp_UATMutexNoWait=1"]

        output_folder = uepyscripts.project.root_folder.joinpath(
            uepyscripts.config["Jenkins"]["OutputFolder"]
        )
        logger.info("Output folder : %s", output_folder)
        if not output_folder.exists():
            raise Exception("The folder where to output the jenkinsfile does not exist")

        uepyscripts.run(
            config.buildgraph.target, config.buildgraph.properties, extra_parameters
        )

        def read_json(path: Path) -> Any:
            with open(path, encoding="utf-8") as f:
                return json.load(f)

        json_nodes = read_json(export_path)

        class BuildNode:
            """Represents a node in the graph of tasks."""

            def __init__(self, json_node):
                self.name = json_node["Name"]
                self.depends_on: list[str] = []

                depends_on = json_node["DependsOn"]
                if depends_on:
                    self.depends_on = depends_on.split(";")

        class BuildGroup:
            """Represents a group of tasks in the build graph."""

            def __init__(self, json_node):
                self.name = json_node["Name"]
                self.nodes = []
                for node in json_node["Nodes"]:
                    self.nodes.append(BuildNode(node))

        class BuildPlatform:
            """Represents a list of groups for a given platform."""

            def __init__(self, name: str):
                self.name = name
                self.job_to_group: dict[str, str] = {}
                self.groups: dict[str, BuildGroup] = {}
                self.parallel_groups: list[list[str]] = []

            def parse_group(self, json_node):
                """Parse a group from the JSON node to associate a node to a group."""
                group = BuildGroup(json_node)
                self.groups.update({group.name: group})

                for node in group.nodes:
                    self.job_to_group.update({node.name: group.name})

            def build_parallel_groups(self):
                """Build a list of tasks that can be executed in parallel."""
                g = Graph()

                for group in self.groups.values():
                    for node in group.nodes:
                        for dependency in node.depends_on:
                            required_group_name = self.job_to_group[dependency]
                            if required_group_name != group.name:
                                g.add_edge(group.name, required_group_name)

                self.parallel_groups = g.topological_sort_with_hierarchy()

        class BuildContext:
            """Context for rendering the build graph template."""

            def __init__(
                self, json_nodes: Any, buildgraph_properties: dict[str, str] = None
            ):
                self.inlined_properties: str = ""
                self.platforms: dict[str, BuildPlatform] = {}

                if buildgraph_properties is not None:
                    for key, value in buildgraph_properties.items():
                        self.inlined_properties += f"-set:{key}={value} "

                for group in json_nodes["Groups"]:
                    platform_name = group["Agent Types"][0]

                    build_platform: BuildPlatform = None
                    if platform_name not in self.platforms:
                        build_platform = BuildPlatform(platform_name)
                        self.platforms[platform_name] = build_platform
                    else:
                        build_platform = self.platforms[platform_name]

                    build_platform.parse_group(group)

                for platform in self.platforms.values():
                    platform.build_parallel_groups()

        build_context = BuildContext(json_nodes, config.buildgraph.properties)

        jobs_template = Template(TEMPLATE)
        return jobs_template.render(ctx=build_context)
